[package]
name = "algorithms_data_structures"
version = "0.1.0"
description = "A set of Cairo 1.0 data structures"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }

[scripts]
# script-name = "command to run"

[lib]
casm = true